name = "NaiveNASflux"
uuid = "85610aed-7d32-5e57-bb50-4c2e1c9e7997"
version = "2.0.13"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaiveNASlib = "bd45eb3e-47ce-54bd-9eaf-e86c5f900853"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ChainRulesCore = "1"
Flux = "0.15"
Functors = "0.2, 0.3, 0.4, 0.5"
JuMP = "0.19, 0.20, 0.21, 0.22, 0.23, 1"
NaiveNASlib = "2.1"
Optimisers = "0.2, 0.3, 0.4"
PrecompileTools = "1"
Reexport = "0.2.0, 1.0"
Setfield = "0.3.4, 0.5, 0.6, 0.7, 0.8, 1.0"
Statistics = "1"
julia = "1"
